### ISSUE TITLE
Hibernate mapping/query issue (thread safety?)

### ISSUE THREAD

**Issue by ctoestreich** [grails/grails-data-mapping#719] opened 2016-05-24 18:02 UTC
Grails 3.1.0
JDK 1.8u72
Linux

Sometimes on booting our application we are seeing hibernate queries become corrupted, not use the dynamic finders and returning the same value set for all queries.  

This only seems to happen on booting a new application via a `java -jar` command against a war/jar and we can't reproduce it in a simple application or locally running inline.

This is the method that gets called:
``` groovy
    @CompileStatic(TypeCheckingMode.SKIP)
    User findUserByUserNameAndSiteId(String userName, Integer siteId = siteService.getCurrentSiteId()) {
        log.info("loading user by by name : " + userName + " and siteid : " + siteId)
        User user = null
        User.withTransaction {
            user = User.findByUserNameAndCmsSiteId(userName?.trim(), siteId)
        }
        log.info("loaded user by by name : " + userName + " : and site id : " + siteId + " and received user : " + user?.userName)
        user
    }
```

This is the output produced via logging.  _Note: I had to scrub some of the fields._

```
12:13:20.756 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] INFO  com.bsb.user.UserSessionService - loading user by by name : PRODecomtest@bluestembrands.com and siteid : 6000
12:13:20.763 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] DEBUG org.hibernate.SQL - select top 1 this_.USER_ID as USER_ID1_1_0_, this_.AUTH_ATTEMPTS as AUTH_ATT2_1_0_, this_.CHOSE_QUESTIONS_FLAG as CHOSE_QU3_1_0_, this_.CMS_SITE_ID as CMS_SITE4_1_0_, this_.CREATED_DATE as CREATED_5_1_0_, this_.CREDIT_APPLICATION_DATE as CREDIT_A6_1_0_, this_.FOP_CUSTOMER_NUMBER as FOP_CUST7_1_0_, this_.LIFE_STAGE as LIFE_STA8_1_0_, this_.LOGIN_FAILURE_COUNT as LOGIN_FA9_1_0_, this_.LOGIN_FAILURE_LOCKOUT_DATE as LOGIN_F10_1_0_, this_.LOGIN_FAILURE_RECOVERY_TOKEN as LOGIN_F11_1_0_, this_.PASSWORD as PASSWOR12_1_0_, this_.PASSWORD_HASH as PASSWOR13_1_0_, this_.PASSWORD_SALT as PASSWOR14_1_0_, this_.REGISTER_COMPUTER_FLAG as REGISTE15_1_0_, this_.RESET_QUESTIONS_EMAIL_FLAG as RESET_Q16_1_0_, this_.RESET_QUESTIONS_EMAIL_TOKEN as RESET_Q17_1_0_, this_.RESET_QUESTIONS_FLAG as RESET_Q18_1_0_, this_.SAFE_LINE_ENROLLED as SAFE_LI19_1_0_, this_.SSN_FAILURE_COUNT as SSN_FAI20_1_0_, this_.SSN_LAST_FAILURE_DATE as SSN_LAS21_1_0_, this_.UPDATED_DATE as UPDATED22_1_0_, this_.USER_NAME as USER_NA23_1_0_ from USERS this_
12:13:20.775 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([USER_ID1_1_0_] : [BIGINT]) - [xxxxxxxxxxxxxx]
12:13:20.775 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([AUTH_ATT2_1_0_] : [INTEGER]) - [8]
12:13:20.775 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([CHOSE_QU3_1_0_] : [CHAR]) - [false]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([CMS_SITE4_1_0_] : [INTEGER]) - [6000]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([CREATED_5_1_0_] : [TIMESTAMP]) - [2015-03-27 10:19:08.727]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([CREDIT_A6_1_0_] : [TIMESTAMP]) - [null]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([FOP_CUST7_1_0_] : [VARCHAR]) - [xxxxxxxxxxxxxx]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([LIFE_STA8_1_0_] : [VARCHAR]) - [Prospect]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([LOGIN_FA9_1_0_] : [INTEGER]) - [5]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([LOGIN_F10_1_0_] : [TIMESTAMP]) - [2016-05-24 11:29:35.867]
12:13:20.776 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([LOGIN_F11_1_0_] : [VARCHAR]) - [null]
12:13:20.777 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([PASSWOR12_1_0_] : [VARCHAR]) - [xxxxxxxxxxxxxx]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([PASSWOR13_1_0_] : [VARCHAR]) - [xxxxxxxxxxxxxx]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([PASSWOR14_1_0_] : [VARCHAR]) - [xxxxxxxxxxxxxx]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([REGISTE15_1_0_] : [CHAR]) - [false]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([RESET_Q16_1_0_] : [CHAR]) - [true]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([RESET_Q17_1_0_] : [VARCHAR]) - [xxxxxxxxxxxxxxxxxxxxxxxxxx]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([RESET_Q18_1_0_] : [CHAR]) - [true]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([SAFE_LI19_1_0_] : [CHAR]) - [null]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([SSN_FAI20_1_0_] : [INTEGER]) - [1]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([SSN_LAS21_1_0_] : [TIMESTAMP]) - [2016-05-24 10:49:16.58]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([UPDATED22_1_0_] : [TIMESTAMP]) - [2016-05-24 11:29:35.873]
12:13:20.778 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.t.descriptor.sql.BasicExtractor - extracted value ([USER_NA23_1_0_] : [VARCHAR]) - [lisaxxxxxxxxxxxxxx@gmail.com]
12:13:20.781 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE org.hibernate.type.CollectionType - Created collection wrapper: [com.bsb.domain.user.User.addresses#xxxxxxxxxxxxxx]
12:13:20.781 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] DEBUG org.hibernate.SQL - select oauth0_.OAUTH_ID as OAUTH_ID1_0_0_, oauth0_.OAUTH_CREATE_DATE as OAUTH_CR2_0_0_, oauth0_.OAUTH_TYPE as OAUTH_TY3_0_0_, oauth0_.PROVIDER_USER_ID as PROVIDER4_0_0_, oauth0_.OAUTH_TOKEN as OAUTH_TO5_0_0_, oauth0_.OAUTH_UPDATE_DATE as OAUTH_UP6_0_0_, oauth0_.user_id as user_id7_0_0_ from OAUTH oauth0_ where oauth0_.user_id=?
12:13:20.782 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] TRACE o.h.type.descriptor.sql.BasicBinder - binding parameter [1] as [BIGINT] - [14913491]
12:13:20.785 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] INFO  com.bsb.user.UserSessionService - loaded user by by name : PRODecomtest@bluestembrands.com : and site id : 6000 and received user : lisaxxxxxxxxxxxxxx@gmail.com
12:13:20.785 bcpaprod106.corp.pgcore.com [http-nio-8080-exec-10] ERROR com.bsb.user.UserSessionService -  User is still lockedOut : lisaxxxxxxxxxxxxxx@gmail.com 
```

The `findByUserName` is being ignored and the query is simply executing a TOP 1 against the user table.  What is also odd is that the first user that was retrieved in this fashion is now stuck and any query against that GORM object always returns the lisaxxxxxxxxxxxxxx@gmail.com user.

We have hibernate caching turned off

``` yml
hibernate.cache.queries: false
hibernate.cache.region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
hibernate.cache.use_query_cache: false
hibernate.cache.use_second_level_cache: false
```

**Comment by ctoestreich** [comment] 2016-05-24 18:06
We are exploring the possibility of one of the tools/processes we have on the box that instruments the code may be corrupting the sql stack in a way that causes hibernate to stick and behave as though it is working when it really isn't.

Once this issue occurs it is corrupted for all domain classes and all supporting queries all ignore finders and simply do a select top 1 from [foo]

**Comment by ctoestreich** [comment] 2016-05-24 18:08
There are no `@Cacheable` annotations anywhere in the stack.

**Comment by ctoestreich** [comment] 2016-05-24 18:13
```
compile "org.grails.plugins:hibernate4"
compile "org.hibernate:hibernate-ehcache"
```

**Comment by robbugh** [comment] 2016-05-24 19:37
We have seen a similar issue with a query loosing a criteria. Though in our case, it occurs after our web-app has been running for a while, not at boot time.

Rob

**Comment by graemerocher** [comment] 2016-05-24 19:55
We will need an example with steps to reproduce

**Comment by ctoestreich** [comment] 2016-05-24 19:56
We may have to get you access via our support contract to our code base directly.  It is stubbornly hard to reproduce for us.

**Comment by ctoestreich** [comment] 2016-05-25 01:31
@robbugh Have you guys turned on sql logging when this happens?  Do you have any more logs stuffs that could help?

**Comment by ctoestreich** [comment] 2016-05-25 15:41
Another commonality that we are seeing this is only in places that use a .withTransaction closure

**Comment by ctoestreich** [comment] 2016-05-25 15:42
the other place we are experiencing this "Stuck" behavior is in this code.

``` groovy
SiteParameter.withTransaction {
         siteParameter = SiteParameter.findByNameAndSiteId(name, siteId)
}
```

**Comment by ColinHarrington** [comment] 2016-05-26 05:16
In cooking up a version with better logging for you to test out I was able to reproduce this issue. 
https://github.com/ColinHarrington/bear

It still wasn't 100% reproducible more like 10% of the time.  After quite a number of attempts, I was able to get a debugger on it and found that the [AbstractHibernateCriterionAdapter.criterionAdaptors](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/query/AbstractHibernateCriterionAdapter.java#L36) were corrupted.  HashMap isn't thread safe and the `criterionAdapters` had 27 values, but listed a `.size()` of 55 in the debugger.  So it appears that there is an issue with the static initialization of the `criterionAdapters`.

**Comment by ColinHarrington** [comment] 2016-05-26 05:18
After doing some more research, it appears that this issue is similar to #643 that was fixed in [release 5.0.2 ](https://github.com/grails/grails-data-mapping/releases/tag/v5.0.2)

**Comment by graemerocher** [comment] 2016-05-26 09:23
@ctoestreich @ColinHarrington could you please try the `5.0.8.BUILD-SNAPSHOT` version using the instructions described here http://grails.io/post/143431711043/how-to-use-a-specific-version-of-gorm-in-grails-3

If you can let me know ASAP as we are trying to get new releases of Grails out by Monday.

**Comment by ctoestreich** [comment] 2016-05-26 14:12
Testing now with 5.0.8.BUILD-SNAPSHOT

**Comment by ColinHarrington** [comment] 2016-05-26 14:49
I haven't been able to reproduce the issue with `5.0.8.BUILD-SNAPSHOT`  I tried 15x and the issue didn't show up.  As a negative use case when I reverted, the issue showed up the 2nd time I ran the load tests. 

Looks like `5.0.8.BUILD-SNAPSHOT` is a good path forward

**Comment by graemerocher** [comment] 2016-05-26 14:49
ok pending feedback from @ctoestreich I have one more bug to fix and will release 5.0.8 shortly. Thanks.

**Comment by ctoestreich** [comment] 2016-05-26 15:09
I can not reproduce with the 5.0.8 snapshot on @ColinHarrington code repo

**Comment by ctoestreich** [comment] 2016-05-26 15:10
I have the snapshot build in our prod app and that will be going live today to test in the wild.

**Comment by graemerocher** [comment] 2016-05-26 16:00
Ok closing for now, if any other issues arise we can re-open

**Closed by graemerocher** 2016-05-26 16:00 UTC
Labels: Awaiting Feedback, In Progress

**Comment by ctoestreich** [comment] 2016-05-26 16:13
This one has a potential for huge repercussions.  It is hard to quantify on the spot, but we had data corruption/financial implications due to this issue and others may be in the same boat.  There should at least be a PSA to upgrade to the community once available.
