### ISSUE TITLE
dateCreated set to null on update for domain with tablePerConcreteClass set

### ISSUE THREAD

**Issue by dpcasady** [grails/grails-data-mapping#937] opened 2017-05-08 22:34 UTC
For GORM 6.1.x, the auto-timestamped `dateCreated` field is set to null on update for a domain like the following:

```groovy
abstract class Vehicle {
    String name
    Date dateCreated

    static mapping = {
        tablePerConcreteClass true
        id generator: 'increment'
    }

}
```

```groovy
class Spaceship extends Vehicle {
}
```

In the following example, the first test passes (`dateCreated` is set successfully), but the second test fails because the `dateCreated` is set to null after the initial insert.
```groovy
void "should set the dateCreated automatically"() {
    given:
    Spaceship ship = new Spaceship(name: "Heart of Gold")
    ship.save(flush: true)

    expect:
    ship.dateCreated != null
}

void "should set the dateCreated automatically on update"() {
    given:
    Spaceship ship = new Spaceship(name: "Heart of Gold")
    ship.save()

    when:
    ship.name = "Heart of Gold II"
    ship.save(flush: true)

    then:
    // DataIntegrityViolationException is thrown:
    // NULL not allowed for column "DATE_CREATED"
    ship.dateCreated != null
}
```
It seems like the `tablePerConcreteClass` and `id` mapping settings are responsible for the problem. With those removed, everything works as expected.

Here's the relevant SQL logging. As you can see, the update statement attempts to set `date_created` to null:
```
DEBUG - org.hibernate.SQL                   : insert into spaceship (version, date_created, name, id) values (?, ?, ?, ?)
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [1] as [BIGINT] - [0]
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [2] as [TIMESTAMP] - [Mon May 08 17:18:52 CDT 2017]
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [3] as [VARCHAR] - [Heart of Gold]
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [4] as [BIGINT] - [1]
DEBUG - org.hibernate.SQL                   : update spaceship set version=?, date_created=?, name=? where id=? and version=?
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [1] as [BIGINT] - [1]
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [2] as [TIMESTAMP] - [null]
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [3] as [VARCHAR] - [Heart of Gold II]
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [4] as [BIGINT] - [1]
TRACE - o.h.type.descriptor.sql.BasicBinder : binding parameter [5] as [BIGINT] - [0]
```

Stacktrace:
```
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; NULL not allowed for column "DATE_CREATED"; SQL statement:
update spaceship set version=?, date_created=?, name=? where id=? and version=? [23502-194]; nested exception is org.h2.jdbc.JdbcSQLException: NULL not allowed for column "DATE_CREATED"; SQL statement:
update spaceship set version=?, date_created=?, name=? where id=? and version=? [23502-194]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertJdbcAccessException(GrailsHibernateTemplate.java:723)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:711)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:302)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:242)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:116)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.performSave(AbstractHibernateGormInstanceApi.groovy:242)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:159)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:152)
	at com.example.SpacechipSpec.$tt__$spock_feature_0_1(SpaceshipSpec.groovy:27)
	at com.example.SpacechipSpec.should set the dateCreated automatically on update_closure2(SpaceshipSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.transaction.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:70)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:67)
	at com.example.SpacechipSpec.should set the dateCreated automatically on update(SpaceshipSpec.groovy)
Caused by: org.h2.jdbc.JdbcSQLException: NULL not allowed for column "DATE_CREATED"; SQL statement:
update spaceship set version=?, date_created=?, name=? where id=? and version=? [23502-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:311)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:793)
	at org.h2.command.dml.Update.update(Update.java:125)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:138)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3132)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3011)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3391)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:145)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.flushSession(AbstractHibernateGormInstanceApi.groovy:280)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.performSave_closure3(AbstractHibernateGormInstanceApi.groovy:245)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:298)
	... 13 more
```

[Example grails 3.2.9/GORM 6.1.3 app](https://github.com/dpcasady/created-by-example) that demonstrates the issue. Run the integration tests and you should see the failure.

**Comment by graemerocher** [comment] 2017-05-29 09:12
The issue is that `save(..)` is being called multiple times. Changing

```
        Spaceship ship = new Spaceship(name: "Heart of Gold")
        ship.save()
```

to

```
        Spaceship ship = new Spaceship(name: "Heart of Gold")
        ship.save(flush:true)
```

Resolves the issue for the update case.

**Comment by graemerocher** [comment] 2017-05-29 10:01
I see no way to fix this currently Hibernate re-reads the objects state for the update prior to firing the insert event which populates the data created property. The correct thing to do is like I said, do not flush the session twice. 

Another alternative which I have committed above is to use `dynamicUpdate`. Otherwise feel free to report the issue to the Hibernate team.

**Closed by graemerocher** 2017-05-29 10:01 UTC
