### ISSUE TITLE
Unique constraint no longer works with Grails 3.3.x and multi tenant

### ISSUE THREAD

**Issue by andersb** [grails/grails-data-mapping#1010] opened 2017-10-06 11:51 UTC
I found information regarding this issue in [https://github.com/grails/grails-core/issues/10481](https://github.com/grails/grails-core/issues/10481)

but something feels strange. With Grails 3.2.8 and GORM 6.1.4 , unique constraint works as expected.
It only fails when upgradring to Grails 3.3.x.

The suggest workaround is to but validation in the service. The problem with that is then schema export will not really take into account that a field is unique and no unique index is created in the database.

But the real question is, can this be fixed to work as with Grails 3.2.8?

### Task List

- [x] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run integration test on attached project.
2. Update to Grails 3.3.1 in gradle.properties
3. Update dependencies in build.gradle (just replaced with commented dependencies) and update the spring boot property to 1.5.7 
4. Update import in IntegrationSpec for Integration annotation
5. Run integration test again

### Expected Behaviour

Test should pass both times

### Actual Behaviour

The second time the test fails with following stack trace.

````
org.springframework.jdbc.BadSqlGrammarException: Hibernate operation: could not extract ResultSet; bad SQL grammar [n/a]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "booking" does not exist  Position: 29
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertJdbcAccessException(GrailsHibernateTemplate.java:723)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:711)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:302)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:242)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.executeWithNewSession(GrailsHibernateTemplate.java:149)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.executeWithExistingOrCreateNewSession(GrailsHibernateTemplate.java:208)
	at org.grails.orm.hibernate.AbstractHibernateDatastore.withNewSession(AbstractHibernateDatastore.java:362)
	at grails.gorm.multitenancy.Tenants.withId_closure1(Tenants.groovy:218)
	at grails.gorm.multitenancy.Tenants$CurrentTenant.withTenant(Tenants.groovy:318)
	at grails.gorm.multitenancy.Tenants.withId(Tenants.groovy:196)
	at org.grails.datastore.gorm.services.DefaultTenantService.withCurrent(DefaultTenantService.groovy:71)
	at se.demo.plugin.IntegrationSpec.$tt__$spock_feature_0_0(IntegrationSpec.groovy:81)
	at se.demo.plugin.IntegrationSpec.test_closure1(IntegrationSpec.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$1.doInTransaction(GrailsTransactionTemplate.groovy:68)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:65)
	at se.demo.plugin.IntegrationSpec.test(IntegrationSpec.groovy)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "booking" does not exist  Position: 29
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2122)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1905)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1881)
	at org.hibernate.loader.Loader.doQuery(Loader.java:925)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342)
	at org.hibernate.loader.Loader.doList(Loader.java:2622)
	at org.hibernate.loader.Loader.doList(Loader.java:2605)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2434)
	at org.hibernate.loader.Loader.list(Loader.java:2429)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1787)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:363)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResultViaListCall(AbstractHibernateQuery.java:801)
	at org.grails.orm.hibernate.query.AbstractHibernateQuery.singleResult(AbstractHibernateQuery.java:791)
	at grails.gorm.DetachedCriteria.get_closure1(DetachedCriteria.groovy:115)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.DetachedCriteria.withPopulatedQuery_closure8(DetachedCriteria.groovy:766)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession_closure22(GormStaticApi.groovy:823)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	at org.grails.datastore.gorm.GormStaticApi.withDatastoreSession(GormStaticApi.groovy:822)
	at grails.gorm.DetachedCriteria.withPopulatedQuery(DetachedCriteria.groovy:737)
	at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:114)
	at grails.gorm.DetachedCriteria.get(DetachedCriteria.groovy:113)
	at org.grails.datastore.gorm.validation.constraints.builtin.UniqueConstraint.processValidate(UniqueConstraint.groovy:75)
	at org.grails.datastore.gorm.validation.constraints.AbstractConstraint.validate(AbstractConstraint.java:88)
	at grails.gorm.validation.DefaultConstrainedProperty.validate(DefaultConstrainedProperty.groovy:601)
	at grails.gorm.validation.PersistentEntityValidator.validatePropertyWithConstraint(PersistentEntityValidator.groovy:296)
	at grails.gorm.validation.PersistentEntityValidator.validate(PersistentEntityValidator.groovy:73)
	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.save(AbstractHibernateGormInstanceApi.groovy:123)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:152)
	at se.demo.plugin.clientdb.BookingService.$tt__saveBooking(BookingService.groovy:11)
	at se.demo.plugin.clientdb.BookingService._mt__saveBooking_closure2(BookingService.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at se.demo.plugin.clientdb.BookingService.saveBooking_closure1(BookingService.groovy)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at grails.gorm.multitenancy.Tenants.withId_closure1$_closure3(Tenants.groovy:225)
	at org.grails.orm.hibernate.GrailsHibernateTemplate$1.doInHibernate(GrailsHibernateTemplate.java:152)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:298)
	... 16 more

````

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** 6.1.4
- **Grails Version (if using Grails):** 3.2.8 , 3.3.1
- **JDK Version:** 1.8.0

### Example Application

[multi-tenancy-demo-plugin.zip](https://github.com/grails/grails-data-mapping/files/1362548/multi-tenancy-demo-plugin.zip)

**Comment by andersb** [comment] 2017-10-06 12:49
After some more testing I found that my note about schema export could still work.
By adding unique:true  under static mapping instead of constraints, the schema export will create the unique index in the database.

**Comment by DanielNoga** [comment] 2018-03-26 06:42
Still broken on Grails 3.3.3 and GORM 6.1.9.RELEASE

**Comment by puneetbehl** [comment] 2018-03-26 15:10
As mentioned by @andersb it seems to be duplicate of  grails/grails-core#10481

**Closed by puneetbehl** 2018-03-26 15:10 UTC
Labels: duplicate

**Comment by DanielNoga** [comment] 2018-03-27 08:46
@puneetbehl Are you sure? Linked bug (https://github.com/grails/grails-core/issues/10481) is about multiple datasources. This problem is about one datasource, only multiple columns
