### ISSUE TITLE
Domain classes marked as dirty without changes on them

### ISSUE THREAD

**Issue by Tirla-Alin** [grails/grails-data-mapping#1307] opened 2020-04-28 10:32 UTC
Domain classes are marked as dirty when any operations are done on the grails.web.databinding.WebDataBinding#getProperties, without actually changing any property.

## Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a simple grails 4.0.1, gorm 7.0.2.RELEASE (with mongo plugin support) application
2. Create 2 simple domain classes 

```
    import groovy.transform.AutoClone

    @AutoClone
    class BuggyCard implements Serializable {
        BuggyCardProfile buggyCardProfile
        
        static hasOne = [buggyCardProfile: BuggyCardProfile]
        static constraints = {
            buggyCardProfile nullable: true
        }
    }
```

```
class BuggyCardProfile implements Serializable {
    BuggyCard buggyCard
    static constraints = {
        buggyCard nullable: true
    }
}
```

3. Insert entities in db

```
BuggyCard.withNewTransaction {
    def card = new BuggyCard()
    card.save(flush: true, failOnError: true)
    def profile = new BuggyCardProfile()
    profile.buggyCard = card
    profile.save(flush: true, failOnError: true)
}
```

4. Create one simple controller with an endpoint.
```
	@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
	def buggyEndpoint() {
                 // todo replace this with the id of the created buggyCard from step 3
		def buggyCard = BuggyCard.findById(1)
		def set = buggyCard.properties.entrySet()
		log.info("is dirty? " + buggyCard.isDirty())

		return respond("result": "result")
	}
```
4. Notice that the entity is dirty.

### Expected Behaviour

Domain classes should not become dirty without actual changes on them.

### Actual Behaviour

Domain classes are marked as dirty without actual changes on them.

### Environment Information

- **Operating System**: macOS Catalina 10.15.4
- **Grails Version:** 4.0.1
- **JDK Version:** 1.8.0_231
- **Container Version (If Applicable):** N/A

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by puneetbehl** [comment] 2020-05-01 11:23
It looks like this is happening because when you call `buggyCard.properties.entrySet()` which calls the hashcode on the `CardProfile` and initializes the proxy. So it looks like this works as intended please check `DirtyCheckable.isDirty` in the following:
https://github.com/grails/grails-data-mapping/blob/7.0.x/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/dirty/checking/DirtyCheckable.groovy#L33

**Comment by Tirla-Alin** [comment] 2020-05-04 08:26
@puneetbehl I don't really understand why it is intended since there is no changes to the actual domain entity. The javadoc of the hasChanged method states that it returns true if the instance has changes. But there are no actual changes. I think the problem is here (or in the code that initializes this field - maybe there are cases where it is not initialized so its null): 
```$changedProperties == null```
https://github.com/grails/grails-data-mapping/blob/7.0.x/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/dirty/checking/DirtyCheckable.groovy#L37
Because if before doing this I call trackChanges I will get no dirty = true.

**Comment by puneetbehl** [comment] 2020-05-04 09:11
I am sorry for the confusion. I believe you are right and the problem is the association proxy also has a field `$changedProperties` which is never initialized. The solution would be to point the same to `$changedProperties` of the target inside the proxy. 

I will soon push a fix for this and testing each of the underline implementations.

**Closed** 2020-05-08 08:35 UTC
Labels: status: pr submitted
