### ISSUE TITLE
Potential bugs in GrailsHibernateTemplate#shouldPassReadOnlyToHibernate()

### ISSUE THREAD

**Issue by rgoldberg** [grails/grails-data-mapping#531] opened 2015-05-30 11:06 UTC
I was trying to understand GORM / Hibernate OSIV settings, and might have discovered some bugs in `GrailsHibernateTemplate#shouldPassReadOnlyToHibernate()`.

I don't know Grails, GORM, Hibernate, Spring, or OSIV much at all, so my understanding might be off, and the potentials bugs below might not actually be bugs.

**Bug 1**
If `osivReadOnly == true`, `passReadOnlyToHibernate == false`, and there's an active read-only transaction, the existing code returns `false`.

Shouldn't `shouldPassReadOnlyToHibernate()` return `true` in this case?

If I'm wrong, and the code should actually return `false`, can you please let me know why?

```
    protected boolean shouldPassReadOnlyToHibernate() {
        if((passReadOnlyToHibernate || osivReadOnly) && TransactionSynchronizationManager.hasResource(getSessionFactory())) {
            if(TransactionSynchronizationManager.isActualTransactionActive()) {
                return passReadOnlyToHibernate && TransactionSynchronizationManager.isCurrentTransactionReadOnly();
            } else {
                return osivReadOnly;
            }
        } else {
            return false;
        }
    }
```

If I am correct, and it should return `true`, substituting the following for the first return statement should fix it:

`return TransactionSynchronizationManager.isCurrentTransactionReadOnly();`

**Bug 2**
Why does the method return `false` if `TransactionSynchronizationManager.hasResource(getSessionFactory()) == false`?

If the `TransactionSynchronizationManager` does not have a `SessionFactory`, I'd imagine that either:

1. the return value of this method won't be used at all
 * if so, why do this check at all? (unless it will frequently fail, and it's a performance optimization, which I highly doubt)
2. a new `SessionFactory` will be created after the call
 * if so, why wouldn't it be able to create a read-only session?
3. some existing `SessionFactory` that isn't in the `TransactionSynchronizationManager` will be used
 * if so, why wouldn't it be able to create a read-only session? Would it possibly use an existing session, for which the current transaction read-only state can't be known in this method?

**Bug 3**
If this method is ever called outside of a view with OSIV enabled (I don't even know if it's possible to disable OSIV), why would `osivReadOnly` even be considered?

I assume that this method is only called from within views, but, if it can be called outside a view, then this might be a bug.

Even if it currently is only called inside views, maybe some check should be added to it to ensure that it is called from within a view to prevent possible future bugs from calling it outside a view. 

**NB:**
The same method definition exists in both the hibernate plugin class:

`org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate`

and in the hibernate4 plugin class:

 `org.grails.orm.hibernate.GrailsHibernateTemplate`

**Comment by lhotari** [comment] 2015-05-30 13:23
> **Bug 1**
> If `osivReadOnly == true`, `passReadOnlyToHibernate == false`, and there's an active read-only transaction, the existing code returns `false`.
> Shouldn't `shouldPassReadOnlyToHibernate()` return `true` in this case?

no.

> If I am correct, and it should return `true`, substituting the following for the first return statement should fix it:
> `return TransactionSynchronizationManager.isCurrentTransactionReadOnly();`

no.

> **Bug 2**
> Why does the method return `false` if `TransactionSynchronizationManager.hasResource(getSessionFactory()) == false`?

`TransactionSynchronizationManager.hasResource(getSessionFactory())` returns true for both OSIV and actual transactions when there is an active session binded to the TransactionSynchronizationManager (which is keeping state in a ThreadLocal).

> 2. a new `SessionFactory` will be created after the call
>  * if so, why wouldn't it be able to create a read-only session?
no. a new session factory won't be created. If you want to learn more about the specific behaviour, it's worth attaching a debugger to a real application.

> If this method is ever called outside of a view with OSIV enabled (I don't even know if it's possible to disable OSIV), why would `osivReadOnly` even be considered?
> I assume that this method is only called from within views, but, if it can be called outside a view, then this might be a bug.
> Even if it currently is only called inside views, maybe some check should be added to it to ensure that it is called from within a view to prevent possible future bugs from calling it outside a view. 

What do you think that the expected behaviour is?

This area of code you pointed out is about using [readonly](http://docs.jboss.org/hibernate/orm/3.5/reference/en-US/html/readonly.html) feature of Hibernate. 
* https://jira.grails.org/browse/GRAILS-10063
* https://jira.grails.org/browse/GRAILS-10064

However there are several problems in using that in Grails with the OSIVI.
OSIVI doesn't isolate changes made in different transactions and the changes might "leak" via the OSIVI session to other transactions. 
A similar problem arises when an item is loaded in a read-only transaction and it's later modified in an actual transaction. The modification will fail because the loaded item is in read-only state in the Hibernate session (OSIV session). These problems are hard hard to debug.

There is 2 configurable settings to control the `osivReadOnly` and `passReadOnlyToHibernate` flags you found in the code:
`grails.hibernate.osiv.readonly` and `grails.hibernate.pass.readonly` . 
The reason there is 2 settings is the problem that OSIV sessions cause: 
* https://jira.grails.org/browse/GRAILS-11177

In Spring OSIVI (which Grails uses) there is a singleSession setting for the Hibernate 3 OSIVI. This setting is missing in Hibernate 4 OSIVI of Spring. 

When using the Hibernate3 plugin, it's usually safe to enable both `grails.hibernate.osiv.readonly` and `grails.hibernate.pass.readonly` setting as long as you have `singleSession=true` in the `hibernate` configuration block of `DataSource.groovy`.
This applies to only `Grails 2.x` applications. For the Hibernate 4 plugin there isn't a solution (yet).

There has been a lot of discussions and effort in this area to solve the problems:
* https://jira.grails.org/browse/GRAILS-11806
* https://jira.spring.io/browse/SPR-12823

I'll close this issue since these aren't bugs that you have pointed out.

**Closed by lhotari** 2015-05-30 13:23 UTC
