### ISSUE TITLE
Embedded mongo documents require _class not to be last element in document

### ISSUE THREAD

**Issue by paulfairless** [grails/grails-data-mapping#721] opened 2016-05-27 10:33 UTC
Hi,

We are migrating a 2.x grails app to Gorm 5 for Mongo 5.0.6, we finally got to the point of trying to load a production snapshot of data but encountered a very strange issue. It appears that when using embedded documents the position of the `_class` attribute in the document is important. 

Grails knows there is an Image, just the object does not get populated with the values from the db

I compared how a new document was created, compared to an existing one, and it was the only difference I could spot. I will try and re-create in a simple app, but this is the behaviour we're seeing:

Original document fails:
```
{
    "_id" : ObjectId("56ec3675e4b07d276c76735f"),
    "dateCreated" : ISODate("2016-03-18T17:10:13.841Z"),
    "datePublished" : ISODate("2016-05-27T09:49:49.031Z"),
    "lastUpdated" : ISODate("2016-05-27T09:49:52.418Z"),
    "title" : "Irene Blazer",
    "description" : "Structured classic-chic blazer in a vibrant blue hue. Tailored for a boxy fit, it's embellished with statement gold buttons that are embossed with a coat of arms.",
    "images" : [ 
        {
            "crop" : {
                "height" : 0,
                "width" : 0,
                "x" : 0,
                "y" : 0,
                "_class" : "Crop",
                "version" : NumberLong(2)
            },
            "height" : 0,
            "master" : false,
            "slug" : "j-crew-irene-blazer",
            "url" : "https://www.filepicker.io/api/file/QT2lvvatR6CC4kYoPaWA",
            "width" : 0,
            "_class" : "Image",
            "version" : NumberLong(14)
        }
    ]
  }
```

using mongo shell directly to move position of `_class`, now this works:
```
{
    "_id" : ObjectId("56ec3675e4b07d276c76735f"),
    "dateCreated" : ISODate("2016-03-18T17:10:13.841Z"),
    "datePublished" : ISODate("2016-05-27T09:49:49.031Z"),
    "lastUpdated" : ISODate("2016-05-27T09:49:52.418Z"),
    "title" : "Irene Blazer",
    "description" : "Structured classic-chic blazer in a vibrant blue hue. Tailored for a boxy fit, it's embellished with statement gold buttons that are embossed with a coat of arms.",
    "images" : [ 
        {
            "_class" : "Image",
            "crop" : {
                "height" : 0,
                "width" : 0,
                "x" : 0,
                "y" : 0,
                "_class" : "Crop",
                "version" : NumberLong(2)
            },
            "height" : 0,
            "master" : false,
            "slug" : "j-crew-irene-blazer",
            "url" : "https://www.filepicker.io/api/file/QT2lvvatR6CC4kYoPaWA",
            "width" : 0,
            "version" : NumberLong(14)
        }
    ]
  }
```

**Comment by graemerocher** [comment] 2016-05-27 11:33
This is by design with the MongoDB codec-based decoder, otherwise we would have to read all of the properties and then re-populate them again into the object, so we cannot as it stand fix this

**Comment by paulfairless** [comment] 2016-05-27 11:52
I see, I didn't think Mongo guaranteed order of fields, but looks like this is supported as of 2.6. Will have to think how to perform a data migration.

**Comment by paulfairless** [comment] 2016-05-27 17:05
Mongo doesn't seem to provide anything in the way of manipulating field order after a document has been inserted, which is making any migration particularly difficult. I was wondering if there are any other ideas to work around this issue?

It seems that `_class` is a new property that does not exist in in our production data. The first load works fine (without any _class field) but upon save it is automatically inserted to the bottom of embedded fields (along with version) causing the issue. Is the `_class` field (or version for that matter) strictly required for embedded documents?

**Comment by graemerocher** [comment] 2016-05-30 05:51
yes removing the inheritance would remove the need for the `_class` field. The other option is to use the mapping engine (which is less efficient) than the new codec engine. See the docs http://gorm.grails.org/latest/mongodb/manual/guide/introduction.html#upgradeNotes

**Comment by graemerocher** [comment] 2016-10-27 09:16
I don't see a possible fix for this, so closing

**Closed by graemerocher** 2016-10-27 09:16 UTC
Labels: mongodb, Won't Fix
