### ISSUE TITLE
Cannot use DomainObject.collection.aggregate() with Maps

### ISSUE THREAD

**Issue by smakela** [grails/grails-data-mapping#647] opened 2016-02-11 16:26 UTC
DomainObject.collection.aggregate() should work also with List of Maps.
GMongo used to do this, but now with MongoExtensions this does not work.
Method should return AggregationOutput, but instead it returns AggregateIterableImpl (because the javadriver aggregate method is called).

Here's project that demonstrates the problem
https://github.com/smakela/mongo-aggregation/

**Comment by graemerocher** [comment] 2016-02-11 16:56
`AggregationOutput` is part of the deprecated MongoDB 2.x API, so that won't be changed

**Comment by smakela** [comment] 2016-02-12 06:26
Ok. But anyways. If you try to iterate through the AggregateIterableImpl you get the ClassCastException, because given objects are Maps and not extend BSON.

**Comment by graemerocher** [comment] 2016-02-12 07:43
The methods are there help with backwards compatibility, but are essentially deprecated in the MongoDB 3.x driver. This is not our choice, this is at the API level in the mongo driver, so there is no point in continuing to support the deprecated APIs. I will go through the methods in `MongoExtensions` and mark the ones that are deprecated in the driver to be also deprecated in GORM for clarity.

For reference you should no longer be using the classes `DBObject`, `DB`, `DBCollection`, `Cursor` etc. these are all part of the old 2.x driver API and are deprecated and have been replaced with `Document`, `MongoDatabase`, `MongoCollection`, `MongoIterable` respectively

**Comment by smakela** [comment] 2016-02-12 08:13
Ok. But the point was if the Grails provides a nicer way of using that MongoDB java driver.

This concerns me in a way that am I going to refactor all the aggregation stuff from the apps to use the Document objects or not.

**Comment by NukeToad** [comment] 2016-12-07 09:44
Hi, is there any fix for this problem ? I'm using Grails 3.2.3 with MongoDB plugin 6.0.4, the result of the aggregation is an instance of com.mongodb.AggregateIterableImpl. 

Is there any workaround to make aggregation work in Grails ? 
I also tried to acess to the Java driver directly, but that didn't work either.

**Comment by graemerocher** [comment] 2016-12-07 10:12
This is not a bug that requires a fix, merely an API change in the MongoDB driver side, you are essentially just using the raw driver API when using aggregation so there is no difference to using the Java driver directly.

See https://github.com/grails/gorm-mongodb/blob/master/grails-datastore-gorm-mongodb/src/test/groovy/org/grails/datastore/gorm/mongo/AggregateMethodSpec.groovy for an example

**Closed** 2016-12-07 10:12 UTC
Labels: mongodb, Not A Bug

**Comment by NukeToad** [comment] 2016-12-07 13:26
Thank you very much, the example was useful to make it work !
The problem was that calling the aggregate method on the collection returns a AggregateIterableImpl object, and it cannot be iterated as it causes a ClassCastException. 

So, instead of using MyDomain.collection.aggregate([...]) (as in all the examples that can be found online...) the aggregate method should be called on the domain object: MyDomain.aggregate([...])

I think it could be a good idea to add an agregation example in the MongoDB plugin documentation to make it clearer.
