### ISSUE TITLE
Gorm 6.1.7.RELEASE, domain class with properties having name of form  {smallFirstChar}{CapitalChar}{AllOtherChars} e.g. iSomeProperty   fails with dynamic finder.

### ISSUE THREAD

**Issue by rushidesai1** [grails/grails-data-mapping#1015] opened 2017-10-10 16:13 UTC
### Task List

- [ ] Steps to reproduce provided
Project is provided to re-create the issue. Run the application and hit TestController. Your should get an error.
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
Example is attached
- [ ] Full description of the issue provided (see below)
In Gorm 6.1.7 if domain has property with pattern like   'iSomeProperty' dynamic finders throw exception. 

In the project attached, if you revert Gorm version to 6.0.10.RELEASE  (in gradle.properties) the same project works.

### Steps to Reproduce

1. Run project attached
2. Hit TestController
3. Make sure Gorm version in gradle.properties is 6.1.7.RELEASE to see the issue

### Expected Behaviour

Dynamic finder should work

### Actual Behaviour

Dynamic finder method blows up

### Environment Information

- **Operating System**: Windows, but any OS should recreate the issue
- **GORM Version:** 6.1.7.RELEASE
- **Grails Version (if using Grails):** 3.2.9     But same issue happens with any higher Grails version if Gorm version is set to 6.1.7/RELEASE
- **JDK Version:** 1.7

### Example Application
[GormIssue.zip](https://github.com/grails/grails-data-mapping/files/1372594/GormIssue.zip)

**Comment by jeffbrown** [comment] 2017-10-10 16:30
Is this a duplicate of #1014?

**Closed** 2017-10-10 16:34 UTC
Labels: duplicate
