### ISSUE TITLE
Database naming is always 'test' with mongodb

### ISSUE THREAD

**Issue by pablovilas** [grails/grails-data-mapping#597] opened 2015-12-02 00:40 UTC
Database naming is always 'test' with mongodb

compile ":mongodb:5.0.0.RC1"
grails 2.5.0

**Comment by graemerocher** [comment] 2015-12-02 07:49
This is because we change the configuration prefix from `grails.mongo` to `grails.mongodb`. I have added a note about this in the upgrade notes: https://github.com/grails/grails-data-mapping/commit/d4ace1daab1645dc56b3d01ff3c92fcb025a99dd#diff-81f3a071c4cfba694d1fb8f2dfd90f00R1

**Comment by pablovilas** [comment] 2015-12-02 14:39
Thanks.

**Comment by mstein** [comment] 2015-12-08 16:37
Have a question about this : in the 3.x branch of the plugin, the `databaseName` property would take the application name by default if if wasn't explicitly specified in the options.
It doesn't seems to be the case anymore, since it is still using the `test` DB if I do not specify anything.

Is this the expected behavior of this new version?

**Comment by graemerocher** [comment] 2015-12-09 07:49
@mstein yeah that sounds like a valid bug that should be fixed

**Closed** 2015-12-11 14:30 UTC
