### ISSUE TITLE
GORM very slow when using mappedBy "none" on self hasMany references

### ISSUE THREAD

**Issue by AdrienGuichard** [grails/grails-data-mapping#1008] opened 2017-10-04 15:46 UTC
When a domain class use hasMany on itself, all objects pointed by this relation are loaded eagerly if using mappedBy "none" (see below). This might leads to big performance penalty if many objects are related.

In the test case, we create 50 objects that are related via relatedSelfRef field to a first object. When displaying the first object in an action, we notice gorm generate 51 select request before displaying the first object name... 

```
package bugeager
class SelfRef {
    String name
    static hasMany = [relatedSelfRef: SelfRef]
    static mappedBy = [relatedSelfRef: "none"]
    static constraints = {
    }
}
```

### Steps to Reproduce

1. launch the test case: `$ ./gradlew bootrun`
2. access test controller, index action `$ wget localhost:8080/test`
3. the standard output will print 51 select requests 

### Expected Behaviour

It would be better if only 1 request were needed...

### Actual Behaviour

It loads 51 objects

### Environment Information

- **Operating System**: Mageia 6, Fedora 24
- **GORM Version:** 6.1.7.RELEASE
- **Grails Version (if using Grails):** 3.3.1
- **JDK Version:** openjdk full version "1.8.0_141-b16"

### Example Application

See next comment,

Thanks for your support,
Adrien

**Comment by AdrienGuichard** [comment] 2017-10-04 15:48
[bugEager.zip](https://github.com/grails/grails-data-mapping/files/1356469/bugEager.zip)

**Comment by AdrienGuichard** [comment] 2017-10-04 17:17
The same test case under Grails 3.2.8 does not show this behavior : only one select is shown...

[bugEager328.zip](https://github.com/grails/grails-data-mapping/files/1356755/bugEager328.zip)

**Comment by AdrienGuichard** [comment] 2017-10-05 17:47
Debuging around "grails.gorm.validation.PersistentEntityValidator", it seems that the entity validation is  accessing object collection.. 

I do not know how to fix this issue properly, and if there is a temporary workaround to avoid cascading validation in this case.

**Comment by graemerocher** [comment] 2017-10-05 18:53
Will investigate. Thanks for the report

**Comment by jameskleeh** [comment] 2017-10-11 04:17
This is a duplicate of #1005

**Closed by jameskleeh** 2017-10-11 04:17 UTC
