### ISSUE TITLE
dynamic finder doesn't work first time, return result when invoked second time.

### ISSUE THREAD

**Issue by naman90** [grails/grails-data-mapping#685] opened 2016-03-30 13:09 UTC
When calling findAllBy method with String [] as argument, invocation throws method missing exception, but when the same method is called second time, it returns the result.
Test case here: 
https://github.com/naman90/GormBug/blob/master/src/test/groovy/gormbug/TestDomainSpec.groovy

**Comment by jeffbrown** [comment] 2016-03-30 13:11
Is that only happening for unit tests?

**Comment by naman90** [comment] 2016-03-30 13:13
No that's happening in dev environment, i created a test case to reproduce the error.

**Comment by graemerocher** [comment] 2016-03-30 13:15
Duplicate of https://github.com/grails/grails-core/issues/9824

**Comment by graemerocher** [comment] 2016-04-01 13:27
calling 

```
response1 =TestDomain."${methodName}"(params)
```
Is not the same as

```
response3 =TestDomain."${methodName}"('Naman','Waterford')
```

The first accepts a single argument which is an array of strings, the second accepts two arguments each of type String. These two are not the same. Replacing the former with a call that uses the spread operator:

```
response1 =TestDomain."${methodName}"(*params)
```

Fixes the problem, since it makes Groovy dispatch to a method takes 2 strings, not an array of String. Full passing test for reference:

```
    void "test GORM when a dynamic finder is invoked second time with string array as arguments"() {
        setup: ''
		String methodName= 'findAllByNameAndCity'
		String[] params= ["Naman","Waterford"]
		def response1
		def response2
		def response3
		when : ' method is called first time'
 	    response1 =TestDomain."${methodName}"(*params)
		
		and : ' when same method is called second time, it finds the result'
		response2 =TestDomain."${methodName}"(*params)
		
		and : ' when invoked with comma separated args, it works all time'
		response3 =TestDomain."${methodName}"('Naman','Waterford')
		
		then: ''
		response1!=null
		response2!=null
		response3!=null
		response2.size()==1
		response3.size()==1
    }
```

**Closed by graemerocher** 2016-04-01 13:27 UTC
Labels: Not A Bug

**Comment by naman90** [comment] 2016-04-04 15:09
Thanks @graemerocher
