### ISSUE TITLE
Add ability to control cascading validation independently from JPA cascade

### ISSUE THREAD

**Issue by longwa** [grails/grails-data-mapping#1150] opened 2018-08-28 20:57 UTC
This is really just an improvement of the implementation for #1106 which added the ability to disable cascading validation in some cases as needed.

The problem with cascading validation based on purely ownership and/or persistence cascade options is that it can end up validating a large number of objects unnecessarily.

This initial fix in #1106 allowed cascade to be disabled for any association that wasn't owned (`isOwningSide = false`). This helps, but the implementation only works for the root entities properties and isn't configurable beyond on and off.

This change proposes changing the (fairly new) mapping property `cascadeValidate` added in #1106 from a `Boolean` to a `String`, which maps to a `CascadeValidateType` with 4 options:

* "none" - Don't do any up-front cascade validation at all for this association
* "default" - The default if not specified, keeps the same behavior as GORM today. Essentially cascades anything that is `isOwningSide` or `doesCascade(MERGE, PERSIST)`.
* "dirty" - Only cascade the association if the associated object (for ToOne) is dirty via the `DirtyCheckable` trait. If the object doesn't implement DirtyCheckable, this will fall back to `default`.
* "owned" - Only cascade validation if the entity owns the associated object, i.e. `isOwningSide = true`

Unlike the `cascades` option, only one String can be given as they all define unique behavior.

Leaving the `cascadeValidate` off or specifying 'default' preserves the current behavior.

This option can be specified globally in `application.groovy` via:
```
grails.gorm.default.mapping = {
    '*'(cascadeValidate: 'dirty')
}
```

I will submit the PR shortly once I complete validation and testing against our main project.

**Comment by graemerocher** [comment] 2018-08-29 06:39
Sounds reasonable, if you send a PR we will need a documentation PR too. Thanks for the contribution.

**Comment by longwa** [comment] 2018-08-29 13:17
Will do. I’m testing it now in our project using ‘dirty’ globally. I’ll give it a week or so under qa and submit both PRs if all looks good

**Comment by zoladkow** [comment] 2018-12-04 15:41
`cascadeValidate` not described in any docs. 

Added same comment as on #1106 since this one here is still open.

**Comment by zoladkow** [comment] 2018-12-04 21:15
Ok, so this should fix the issue I mentioned (https://github.com/grails/grails-data-mapping/issues/1106#issuecomment-444252064) with original `cascadeValidate` solution. Where deep validation is not considering `cascadeValidate` on deeper associations.

**Comment by zoladkow** [comment] 2018-12-05 09:05
@longwa please do submit a PR! 
Even if there are still some gotchas, this implementation with multiple options would also fix the transitive issue with `cascadeValidate`. Since here `doesCascadeValidate()` is on `Association` so it's looking at mapping options on the right entity.

With how aggressive validation have become, this is the only option to prevent validation from going where it's not needed (ie. an entity already persisted). I will abuse of `none`.

**Comment by demon101** [comment] 2018-12-27 16:20
@longwa please, make PR. In our project we can't fix all by cascadeValidate: false for has many associations.

**Comment by demon101** [comment] 2018-12-27 17:14
@graemerocher new strict validation works sometimes very slow. The setting can be a good workaround for some grails 3.2-> 3.3 upgrade cases.  
Could you assign this issue to coming 6.1.11 version, please?

**Comment by longwa** [comment] 2018-12-27 19:08
I’ll create a PR once I’m back from the holiday break. I want to get the changes merged into the mainline anyway as we are running with a custom build locally. The only hold up is that I need to create a documentation PR as well.

**Comment by demon101** [comment] 2018-12-27 20:08
@longwa we can help with documentation!

**Comment by graemerocher** [comment] 2018-12-28 15:57
https://github.com/grails/grails-data-mapping/pull/1061 might be related, but that is missing a test

**Comment by demon101** [comment] 2019-01-03 07:55
We tried to migrate our project from grails 3.2.11 to 3.2.9. But we can't.
During testing, we found 18 strange bugs, most of them was caused by aggressive validation. We inserted about 100 cascadeValidate in mappings, but in some cases the option not work. 
At the result, we jump back to 3.2.11 one day before release and now our test team looks very aggressive.

@graemerocher could you assign 6.1.12 version to the issue. Aggressive cascade validation issues are a real blocker for us. Thx!

**Comment by graemerocher** [comment] 2019-01-03 08:04
Have you tested the changes in #1061 ?

**Comment by zoladkow** [comment] 2019-01-03 12:57
Hi @graemerocher, #1061 should be included for logical consistency. The code speaks for itself - that `association.doesCascade(...)` was out of place. At point where we're already analyzing `associatedEntity` and want to drill down into `associatedPersistentProperty`. 

It's a similar logical error that prevented change #1106 from working as expected (only root level `cascadeValidate` was checked, preventing control of deeper validations).

**Comment by graemerocher** [comment] 2019-01-03 13:20
I have merged #1061 will await the PR from @longwa to take this issue forward.

**Comment by longwa** [comment] 2019-02-22 19:31
Just FYI, the change from @zoladkow isn't really relevant anymore in the context of this PR as the recursion that happens already makes that check inside of the `cascadeToAssociativeProperty`. In fact, the check wasn't needed at all as that check is done before `cascadeValidationToOne` is even called in the first place for the `association` and `associatedObject`.

**Comment by Relaximus** [comment] 2019-02-27 15:54
I have added the docs for this. 
@longwa could you check the doc also for any discrepancy. Thanks.

**Comment by zoladkow** [comment] 2019-06-24 21:04
@graemerocher Am I missing something or is it that in 3.3.10 / 6.1.12 the global way of setting `cascadeValidate` is not possible?

Thats my entire `application.groovy` file:
```groovy
grails.gorm.default.mapping = {
    '*'(cascadeValidate: 'none')
}
```

**Comment by zoladkow** [comment] 2019-06-25 07:56
@longwa @graemerocher 
Guys, after another legacy project migration effort (3.0.17 -> 3.3.10) I must thank you for this change. 

At first I did not know that it actually went into latest release and still used `cascadeValidate: false` (and since this is still open) but then tried with global mapping options to have the expected saving behavior back (`'none'`). And that works like a charm! :)

**Comment by longwa** [comment] 2019-08-26 00:49
@graemerocher I believe the code is pulled into the GORM 7.x line as well as the documentation PR submitted by relaximus. Any reason not to close this out?

**Comment by demon101** [comment] 2019-10-06 19:37
@jameskleeh I believe the issue can be closed

**Comment by matero** [comment] 2020-03-27 18:25
@longwa is `cascadeValidate: 'none'` a valid option on `toMany` associations? We need the collection to be validated, but not its contents and I don't understand if this option would help us

**Comment by matero** [comment] 2020-03-27 18:37
another question, is this merged into **GORM 6.1.x** @longwa @graemerocher ?

**Comment by graemerocher** [comment] 2020-03-27 21:26
I don’t believe so

**Closed** 2020-03-27 21:26 UTC

**Comment by longwa** [comment] 2020-03-27 22:42
@matero Yes, setting it to `'none'` on a toMany will prevent it from calling validate on each object in the collection but it should still validate the collection attributes themselves (minSize, etc.) if that's what you mean. We use `dirty` globally which seems like a nice balance since we don't really want to validate anything that isn't considered dirty. Keep in mind it will still validate them on flush if they are truly dirty.

It looks like the change is in v6.1.2 and v7.0.3

https://github.com/grails/grails-data-mapping/commit/9761c3e71dc213443f505314449cc5191c51f057

Hope that helps.

**Comment by matero** [comment] 2020-03-28 00:18
Thanks! That's awesome :)
