### ISSUE TITLE
GormEntity.saveAll(Iterable) in GORM 6 with Hibernate 5 fails with a java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by sbearcsiro** [grails/grails-data-mapping#879] opened 2017-02-22 00:57 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Grails 3.2.6 application using GORM 6 and Hibernate 5
2. Add a domain object
3. Add some code to create some domain objects
4. Add some code which loads a collection of domain objects, updates a property and then call `Domain.saveAll(collection)`

### Expected Behaviour

All the changes should be persisted to the database

### Actual Behaviour

The saveAll fails with a `java.lang.IncompatibleClassChangeError`

### Environment Information

- **Grails Version:** 3.2.6
- **JDK Version:** 1.8.121

### Example Application

- https://github.com/sbearcsiro/grails3-hib5-saveall

The full stacktrace from this [demo](https://github.com/sbearcsiro/grails3hib5saveall) is:

```
java.lang.IncompatibleClassChangeError: Found interface org.hibernate.engine.spi.EntityEntry, but class was expected
        at org.grails.orm.hibernate.EventTriggeringInterceptor.onSaveOrUpdate(EventTriggeringInterceptor.java:105)
        at org.grails.orm.hibernate.EventTriggeringInterceptor.onPersistenceEvent(EventTriggeringInterceptor.java:90)
        at org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener.onApplicationEvent(AbstractPersistenceEventListener.java:51)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
        at org.grails.datastore.gorm.events.ConfigurableApplicationContextEventPublisher.publishEvent(ConfigurableApplicationContextEventPublisher.groovy:30)
        at org.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.publishEvent(ClosureEventTriggeringInterceptor.java:148)
        at org.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor.onSaveOrUpdate(ClosureEventTriggeringInterceptor.java:78)
        at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:682)
        at org.hibernate.internal.SessionImpl.save(SessionImpl.java:674)
        at org.hibernate.internal.SessionImpl.save(SessionImpl.java:669)
        at org.grails.orm.hibernate.GrailsHibernateTemplate.save(GrailsHibernateTemplate.java:715)
        at org.grails.orm.hibernate.AbstractHibernateSession.persist(AbstractHibernateSession.java:123)
        at org.grails.datastore.gorm.GormStaticApi$_saveAll_closure4.doCall(GormStaticApi.groovy:254)
        at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:318)
        at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
        at org.grails.datastore.gorm.GormStaticApi.saveAll(GormStaticApi.groovy:253)
        at org.grails.datastore.gorm.GormEntity$Trait$Helper.saveAll(GormEntity.groovy:487)
        at threetwosixtest.IndexController.index(IndexController.groovy:8)
```

It appears to be caused by grails-datastore-gorm-hibernate-core being compiled against Hibernate 4, with EntityEntry having changed from a class to an interface in Hibernate 5

**Comment by graemerocher** [comment] 2017-02-24 08:04
Interesting we have tests for this: https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-tck/src/main/groovy/grails/gorm/tests/SaveAllSpec.groovy

And they run fine in our test suite and hit the break point on line 105 of `EventTriggeringInterceptor`, it must be that certain JVMs are more sensitive to this than others.

**Comment by graemerocher** [comment] 2017-02-24 08:05
I've pushed a fix, although since I cannot reproduce no associated test. Let me know if it resolves the issue.

**Closed by graemerocher** 2017-02-24 08:05 UTC

**Comment by sbearcsiro** [comment] 2017-02-25 06:40
@graemerocher  thanks, I tested the fix with my example and it solves the problem :+1: 

FWIW I could get the exception running my example against Oracle Java 7u80 on Ubuntu + MacOS, Oracle Java 8u121 on Ubuntu + MacOS and OpenJDK 8u121 on Ubuntu.
